name: Build Flutter Web and commit build/web

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.0'

      - name: Install deps
        run: flutter pub get

      # יוצר קובץ _headers בתוך web כדי ש-Render יוסיף CSP שמתיר eval
      - name: Ensure CSP headers for Render
        run: |
          mkdir -p web
          cat > web/_headers << 'EOF'
          /*
            Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src *; object-src 'none'
          EOF

      # בילד יחיד עם renderer html, בלי PWA, ועם source maps לזיהוי שגיאות
      - name: Build web (html renderer, no PWA, source maps)
        run: flutter build web --release --web-renderer html --no-tree-shake-icons --pwa-strategy=none --source-maps

      - name: Commit build/web back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f build/web
          git commit -m "CI: update build/web [skip ci]" || echo "No changes"
          git push
