name: Build Flutter Web and update build/web

on:
  workflow_dispatch:
  push:
    paths:
      - "lib/**"
      - "web/**"
      - "pubspec.yaml"
      - ".github/workflows/deploy.yml"

permissions:
  contents: write

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.24.0"

      - name: Flutter pub get
        run: flutter pub get

      # יוצר קובץ _headers מאובטח ללא unsafe-eval
      - name: Ensure CSP headers (secure)
        run: |
          mkdir -p web
          cat > web/_headers << 'EOF'
          /*
            Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self' https: http: ws: wss:; worker-src 'self' blob:; object-src 'none'
          EOF

      # Build תואם CSP ללא eval
      - name: Build web release with CSP
        run: flutter build web --release --web-renderer html --csp --pwa-strategy=none --no-tree-shake-icons

      - name: Copy _headers to build
        run: cp web/_headers build/web/_headers

      # Fallback במקרה שהפלטפורמה מתעלמת מ-_headers
      - name: Add static.json fallback
        run: |
          cat > build/web/static.json << 'EOF'
          {
            "headers": {
              "/**": {
                "Content-Security-Policy": "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self' https: http: ws: wss:; worker-src 'self' blob:; object-src 'none'"
              }
            }
          }
          EOF

      # דחיפת build/web לענף הנוכחי, עם טיפול נכון ב-rebase
      - name: Commit and push build/web
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -f build/web
          git diff --cached --quiet || git commit -m "CI: update build/web [skip ci]"

          git fetch origin
          git -c rebase.autoStash=true pull --rebase origin ${{ github.ref_name }} || true
          git push origin HEAD:${{ github.ref_name }}
